language: node_js
dist: trusty
node_js:
  - "12"
cache:
  - npm
  - yarn
install:
  - yarn
  - npm install cypress --save-dev

before_script:
  - npm start -- --silent &

script:
  - cypress run

addons:
  artifacts:
    bucket: "shirohige-travis-ci-artifacts"
    paths:
      - ./coverage/*
      - ./cypress/screenshots/*
      - ./cypress/videos/*
